config/routes.rb
Rails.application.routes.draw do
  get 'test/flow'

  get 'test/grid'

	root 'pages#index'

  get 'pages/about'

  get 'pages/services'

  get 'pages/contact'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def services
  end

  def contact
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def flow
  end

  def grid
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/layouts/_footer.html.erb
  <div class="reset">
  <div class="row">
    <div class="col s6">
     © 2017 Copyright
    </div>
      <div class="col s6">
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">test1</a></li>
  <li><a href="#!">test2</a></li>
  <li><a href="#!">test3</a></li>
</ul>
<ul id="dropdown2" class="dropdown-content">
  <li><a href="#!">test1</a></li>
  <li><a href="#!">test2</a></li>
  <li><a href="#!">test3</a></li>
</ul>

<nav>
<div class="nav-wrapper">

	<%= link_to root_path, class:"brand-logo" do %>
        	<i class="material-icons left">cloud</i>Unicorn
      		<% end %>
      		
  <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
  <ul class="right hide-on-med-and-down">
     <li><%= link_to 'About', pages_about_path %></li>
    <li><%= link_to 'Services', pages_services_path %></li>
    <li><%= link_to pages_contact_path do %>
        	<i class="material-icons left">email</i>Contact
      		<% end %>
    </li>

    <!-- Dropdown Trigger -->
    <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
  </ul>
  <ul class="side-nav" id="mobile-demo">
     <li><%= link_to 'About', pages_about_path %></li>
    <li><%= link_to 'Services', pages_services_path %></li>
    <li><%= link_to pages_contact_path do %>
        <i class="material-icons left">email</i>Contact
      	<% end %>
    </li>

    <!-- Dropdown Trigger -->
    <li><a class="dropdown-button" href="#!" data-activates="dropdown2">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
  </ul>
</div>
</nav>



       

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test Site</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<script type="text/javascript">
			$(document).on('turbolinks:load', function(){
			$(".button-collapse").sideNav();
			});
</script>

  </head>

  <body>

  	<header>
	  	<%= render 'layouts/navbar' %>
		</header>
	  
	  <main>
		  <div class="container">
		    <%= yield %>
			</div>
		</main>
	  
	  <footer class="page-footer">
	  	<%= render 'layouts/footer' %>
	 	</footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="row">
<div class="col s12 m6 l6">
	<h5>Text block</h5>
	<p class="flow-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
</div>
<div class="col s12 m6 l6">
	<h5>Text block</h5>
	<p class="flow-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
</div>
</div>

app/views/pages/contact.html.erb
<div class="row">
	<div class="col s12">
		<h5>Contact</h5>
		<p class="flow-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
		</p>
  </div>
</div>

<div class="row">
  <form class="col s12">
    <div class="input-field col s12  l6">
      <input id="first_name" type="text" class="validate">
      <label for="first_name">First Name</label>
    </div>
    <div class="input-field col s12 l6">
      <input id="last_name" type="text" class="validate">
      <label for="last_name">Last Name</label>
    </div>
    <div class="input-field col s12">
      <input id="email" type="email" class="validate">
      <label for="email">Email</label>
    </div>
      <div class="input-field col s12">
        <textarea id="textarea1" class="materialize-textarea"></textarea>
        <label for="textarea1">Comments</label>
      </div>
    <div class="row center-button">
      <a class="waves-effect waves-light btn">Submit</a>
    </div>
  </form>
</div>

app/views/pages/index.html.erb
<div class="row">
    <div class="col s12"><p>s12</p></div>
    <div class="col s12 m4 l2"><p>s12 m4</p></div>
    <div class="col s12 m4 l8"><p>s12 m4</p></div>
    <div class="col s12 m4 l2"><p>s12 m4</p></div>
  </div>
  <div class="row">
    <div class="col s12 m6 l3"><p>s12 m6 l3</p></div>
    <div class="col s12 m6 l3"><p>s12 m6 l3</p></div>
    <div class="col s12 m6 l3"><p>s12 m6 l3</p></div>
    <div class="col s12 m6 l3"><p>s12 m6 l3</p></div>
  </div>

app/views/pages/services.html.erb
<div class="row">
  <h5>Services</h5>
  <div class="col s12 m6 l6">
    <div class="card white">
      <div class="card-content black-text">
        <span class="card-title">Card Title</span>
        <p>I am a very simple card. I am good at containing small bits of information.
        I am convenient because I require little markup to use effectively.</p>
      </div>
      <div class="card-action">
        <a href="#">This is a link</a>
        <a href="#">This is a link</a>
      </div>
    </div>
  </div>
  <div class="col s12 m6 l6">
    <div class="card white">
      <div class="card-content black-text">
        <span class="card-title">Card Title</span>
        <p>I am a very simple card. I am good at containing small bits of information.
        I am convenient because I require little markup to use effectively.</p>
      </div>
      <div class="card-action">
        <a href="#">This is a link</a>
        <a href="#">This is a link</a>
      </div>
    </div>
  </div>
  <div class="col s12 m6 l6">
    <div class="card white">
      <div class="card-content black-text">
        <span class="card-title">Card Title</span>
        <p>I am a very simple card. I am good at containing small bits of information.
        I am convenient because I require little markup to use effectively.</p>
      </div>
      <div class="card-action">
        <a href="#">This is a link</a>
        <a href="#">This is a link</a>
      </div>
    </div>
  </div>
  
  </div>
</div>